---
title: "Optimal Partitioning"
#author: "Anuraag Srivastava"
#date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{opart}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(opart)
library(microbenchmark)
library(data.table)
library(directlabels)
library(ggplot2)
library(fpop)
library(changepoint)
```

In this vignette we will use neuroblastoma data set to compare the run times of opart with Fpop and cpt.mean.

```{r}
data(neuroblastoma, package="neuroblastoma")
selectedData <- subset(neuroblastoma$profiles, profile.id=="1" & chromosome=="1")
opart_gaussian(selectedData$logratio, 1)$end.vec
```


Using microbenchmark to compare run times we get:

```{r}
selected_ids = unique(neuroblastoma$profiles$profile.id)
selected_data = neuroblastoma$profiles
num_tests = length(selected_ids)
timing_list = list()
n = 1
while(n <= 50){
  current_id = selected_ids[n]
  current_data = subset(selected_data, profile.id == current_id)
  length = length(current_data$logratio)
  timing = microbenchmark(
  "fpop"={
      Fpop(current_data$logratio, 1)
    },
  "cpt_mean"={
      cpt.mean(current_data$logratio, pen.value=1)
    },
   "opart_gaussian"={
        opart_gaussian(current_data$logratio, 1)
    }, times=5)
  
  
  timing_list[[paste(n)]] = data.table(length, timing)
  n = n + 1
}

timing.dt = do.call(rbind, timing_list)
```

```{r fig.height = 5, fig.width = 10}

p <- ggplot(data = timing.dt, aes(x = log(timing.dt$length), 
                             y = log(timing.dt$time), 
                             col = timing.dt$expr))+
  geom_smooth() +
  labs(x="log(size)", y="log(time(ms))", col="method")

direct.label(p, "last.polygons")
```

